---
title: "NFL Draft Data"
author: "Julianna Alvord"
date: "10/22/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(dplyr)
```

```{r}
#using example rvest code
url <- "https://www.google.de/?#q=list+breweries+chicago"
browseURL(url)
url <- "http://thehopreview.com/blog/chicago-brewery-list"
browseURL(url)
content <- read_html(url, encoding = "utf8")
anchors <- html_nodes(content, css = "#block-yui_3_17_2_8_1438187725105_11398 p")
breweries <- html_text(anchors)
length(breweries)
head(breweries)
breweries <- breweries[-1]
```

```{r}
#scraping 2018 draft data
url<- "https://en.wikipedia.org/wiki/2018_NFL_Draft"

draft18 <- url %>%
  read_html() %>%
  html_nodes(xpath = '//*[@id="mw-content-text"]/div/table[3]') %>%
  html_table()

draft18 <- draft18[[1]]

#this works for 2018-2015
```

```{r}
#bringing in pbp data
pbp_2018 <- read.csv("pbp-2018.csv")

#filtering for mayfield or barkley
pbp_2018_filtered <- pbp_2018 %>%
  mutate(barkley = ifelse(grepl("BARKLEY", Description, fixed = TRUE), 1, 0),
         mayfield = ifelse(grepl("MAYFIELD", Description, fixed = TRUE), 1, 0)) %>%
  filter(barkley == 1|mayfield == 1) %>%
  mutate(player = ifelse(barkley == 1, "barkley",
                         ifelse(mayfield == 1, "mayfield", "both")))


#how successful are they?
pbp_yards <- pbp_2018_filtered %>%
  group_by(player) %>%
  summarise(mean_yards = mean(Yards),
            median_yards = median(Yards),
            min_yards = min(Yards),
            max_yards = max(Yards))

#plotting distribution of yards
ggplot(pbp_2018_filtered, aes(Yards, fill = player)) + geom_density(alpha = 0.6)
#similar distributions
```

